/**
 * GENERATED FILE — DO NOT EDIT.
 *
 * Source of truth: packages/poster-contract/src/*.ts (zod schemas)
 * Regenerate:     pnpm -F @suite/poster-contract gen
 *
 * Emitted by openapi-typescript from packages/poster-contract/openapi.json.
 */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/oauth/token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Exchange client credentials for a short-lived app token
     * @description Form-encoded, per OAuth2. The returned JWT is valid for 15 minutes and its sub claim identifies the app. App credentials alone never authorize publishing: acting for a user also requires that user’s grant.
     */
    post: operations['createToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/context': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Report who the API thinks you are
     * @description Returns the acting app and user for the presented token. The response shape is identical in both auth modes, which makes it the cheapest way for a client to confirm its credentials and the user it is acting for.
     */
    get: operations['getAuthContext'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description OAuth2 client-credentials request, form-encoded. */
    TokenRequest: {
      /** @enum {string} */
      grant_type: 'client_credentials';
      client_id: string;
      client_secret: string;
    };
    /** @description A short-lived app access token. */
    TokenResponse: {
      /** @description JWT whose sub is the app id. */
      access_token: string;
      /** @enum {string} */
      token_type: 'Bearer';
      /** @description Seconds until the token expires. */
      expires_in: number;
    };
    /** @description Who the API thinks you are. Identical shape in both auth modes. */
    AuthContext: {
      /**
       * @description Which auth mode the caller used.
       * @enum {string}
       */
      mode: 'app' | 'user';
      app: {
        /** @description The app the request acts as. */
        client_id: string;
        first_party: boolean;
      };
      /**
       * Format: uuid
       * @description The user this request acts on behalf of, or null in app mode with no user.
       */
      user_id: string | null;
    };
    /** @description The single error envelope used by every non-2xx response. */
    ErrorEnvelope: {
      error: {
        /**
         * @description Machine-readable error code.
         * @enum {string}
         */
        code:
          | 'invalid_request'
          | 'invalid_token'
          | 'forbidden_user'
          | 'grant_missing'
          | 'not_found'
          | 'idempotency_conflict'
          | 'too_late'
          | 'constraint_violation'
          | 'rate_limited'
          | 'internal_error';
        /** @description Human-readable summary. Never used for control flow. */
        message: string;
        details?: {
          /** @description Index of the failing target in the submitted targets array. */
          target_index: number;
          /** @description Public id of the target connection. */
          connection_id?: string;
          /** @description Constraint code; see the contract §8 list. */
          code: string;
          /** @description The limit that was exceeded and the actual value, as data. */
          constraint?: {
            [key: string]: unknown;
          };
        }[];
        /** @description Echoes the X-Request-Id response header. Quote it in support requests. */
        request_id: string;
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type SchemaTokenRequest = components['schemas']['TokenRequest'];
export type SchemaTokenResponse = components['schemas']['TokenResponse'];
export type SchemaAuthContext = components['schemas']['AuthContext'];
export type SchemaErrorEnvelope = components['schemas']['ErrorEnvelope'];
export type $defs = Record<string, never>;
export interface operations {
  createToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/x-www-form-urlencoded': components['schemas']['TokenRequest'];
      };
    };
    responses: {
      /** @description A new access token. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenResponse'];
        };
      };
      /** @description Malformed request or unsupported grant_type. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description Unknown client_id, wrong client_secret, or disabled app. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description Too many token requests; honor Retry-After. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  getAuthContext: {
    parameters: {
      query?: {
        /** @description The user to act as. Required in app mode for user-scoped work; in user mode it must equal the token subject or the request is rejected with forbidden_user. */
        user_id?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The resolved auth context. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthContext'];
        };
      };
      /** @description Missing, malformed, or expired token. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description User-mode token does not match the requested user_id. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description Per-app rate limit exceeded; honor Retry-After. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
}
